export const subjects = [
    "All Subjects", "Acoustic Guitar", "Electric Guitar", "Bass Guitar", "Violin",
    "Piano", "Keyboard", "Harmonium", "Ukulele", "Drums", "Tabla", "Mrudangam",
    "Western Vocal", "Carnatic Vocals", "Hindustani Vocals", "Flute", "Saxophone",
    "Trumpet", "Sitar", "Veena",
];

export const languages = ["All Languages", "English", "Hindi", "Tamil", "Telugu", "Kannada", "Malayalam", "Bengali", "Marathi"];
export const levels = ["All Levels", "Beginner", "Intermediate", "Advanced"];

export const teachers = [
    {
        id: 1,
        name: "Rahul Sharma",
        subjects: ["Acoustic Guitar", "Electric Guitar", "Bass Guitar"],
        languages: ["English", "Hindi"],
        level: ["Beginner", "Intermediate"],
        rating: 4.9,
        reviews: 142,
        experience: "8 years",
        price: "₹800/class",
        trialPrice: "Free",
        bio: "Professional guitarist with 8+ years of teaching experience. Trained from Trinity College of Music, London.",
        image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&q=80",
        badges: ["Trinity Certified", "Top Rated"],
    },
    {
        id: 2,
        name: "Priya Nair",
        subjects: ["Piano", "Keyboard"],
        languages: ["English", "Malayalam", "Tamil"],
        level: ["Beginner", "Intermediate", "Advanced"],
        rating: 4.8,
        reviews: 118,
        experience: "10 years",
        price: "₹1000/class",
        trialPrice: "Free",
        bio: "ABRSM Grade 8 pianist with a decade of teaching students of all age groups.",
        image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&q=80",
        badges: ["ABRSM Certified", "Top Rated"],
    },
    {
        id: 3,
        name: "Amit Desai",
        subjects: ["Drums", "Tabla"],
        languages: ["English", "Hindi", "Marathi"],
        level: ["Beginner", "Intermediate"],
        rating: 4.7,
        reviews: 96,
        experience: "6 years",
        price: "₹750/class",
        trialPrice: "Free",
        bio: "Versatile percussionist adept at both Western drums and classical Tabla. Berklee alumnus.",
        image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&q=80",
        badges: ["Berklee Alumnus"],
    },
    {
        id: 4,
        name: "Deepa Krishnan",
        subjects: ["Carnatic Vocals", "Western Vocal"],
        languages: ["Tamil", "English", "Telugu"],
        level: ["Beginner", "Intermediate", "Advanced"],
        rating: 4.9,
        reviews: 204,
        experience: "15 years",
        price: "₹900/class",
        trialPrice: "Free",
        bio: "Renowned Carnatic vocalist and A-grade artist of All India Radio with 15 years of teaching excellence.",
        image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=300&q=80",
        badges: ["AIR A-Grade Artist", "Top Rated"],
    },
    {
        id: 5,
        name: "Sanjay Mehta",
        subjects: ["Violin", "Sitar"],
        languages: ["English", "Hindi", "Gujarati"],
        level: ["Beginner", "Intermediate"],
        rating: 4.6,
        reviews: 78,
        experience: "7 years",
        price: "₹850/class",
        trialPrice: "Free",
        bio: "Classical string musician trained under maestro Pandit Ravi Shankar's disciples.",
        image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&q=80",
        badges: ["Classical Expert"],
    },
    {
        id: 6,
        name: "Meena Pillai",
        subjects: ["Flute", "Keyboard"],
        languages: ["Malayalam", "English", "Tamil"],
        level: ["Beginner", "Intermediate"],
        rating: 4.8,
        reviews: 89,
        experience: "9 years",
        price: "₹800/class",
        trialPrice: "Free",
        bio: "Classical and contemporary flute artist with extensive experience teaching online and offline.",
        image: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=300&q=80",
        badges: ["Trinity Certified"],
    },
    {
        id: 7,
        name: "Kiran Rao",
        subjects: ["Acoustic Guitar", "Ukulele"],
        languages: ["Kannada", "English", "Hindi"],
        level: ["Beginner"],
        rating: 4.7,
        reviews: 65,
        experience: "4 years",
        price: "₹650/class",
        trialPrice: "Free",
        bio: "Specializes in beginner-friendly guitar lessons with a fun and engaging teaching style.",
        image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&q=80",
        badges: ["Beginner Specialist"],
    },
    {
        id: 8,
        name: "Ananya Singh",
        subjects: ["Hindustani Vocals", "Harmonium"],
        languages: ["Hindi", "English", "Bengali"],
        level: ["Beginner", "Intermediate", "Advanced"],
        rating: 4.9,
        reviews: 177,
        experience: "12 years",
        price: "₹950/class",
        trialPrice: "Free",
        bio: "Acclaimed Hindustani vocalist performing at prestigious sabhas across India and abroad.",
        image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&q=80",
        badges: ["National Awardee", "Top Rated"],
    },
    {
        id: 9,
        name: "Vikram Nambiar",
        subjects: ["Mrudangam", "Tabla"],
        languages: ["Malayalam", "Tamil", "English"],
        level: ["Beginner", "Intermediate", "Advanced"],
        rating: 4.8,
        reviews: 103,
        experience: "11 years",
        price: "₹880/class",
        trialPrice: "Free",
        bio: "Senior Mrudangam artist trained in the Palakkad Mani Iyer tradition. Performed internationally.",
        image: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=300&q=80",
        badges: ["Palakkad Tradition"],
    },
];

export const states = [
    "Andhra Pradesh", "Karnataka", "Kerala", "Maharashtra", "Tamil Nadu",
    "Telangana", "Delhi", "Gujarat", "Rajasthan", "West Bengal",
    "Uttar Pradesh", "Punjab", "Haryana", "Madhya Pradesh", "Odisha",
];

export const citiesByState: Record<string, string[]> = {
    "Karnataka": ["Bangalore", "Mysore", "Hubli", "Mangalore", "Belgaum"],
    "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Salem", "Trichy"],
    "Maharashtra": ["Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad"],
    "Telangana": ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar"],
    "Kerala": ["Kochi", "Thiruvananthapuram", "Kozhikode", "Thrissur"],
    "Andhra Pradesh": ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore"],
    "Delhi": ["New Delhi", "Dwarka", "Rohini", "Saket", "Lajpat Nagar"],
    "Gujarat": ["Ahmedabad", "Surat", "Vadodara", "Rajkot"],
    "West Bengal": ["Kolkata", "Howrah", "Durgapur", "Asansol"],
    "Uttar Pradesh": ["Lucknow", "Kanpur", "Agra", "Varanasi", "Noida"],
    "Rajasthan": ["Jaipur", "Jodhpur", "Udaipur", "Kota"],
    "Punjab": ["Chandigarh", "Amritsar", "Ludhiana", "Jalandhar"],
    "Haryana": ["Gurugram", "Faridabad", "Hisar", "Panipat"],
    "Madhya Pradesh": ["Bhopal", "Indore", "Gwalior", "Jabalpur"],
    "Odisha": ["Bhubaneswar", "Cuttack", "Rourkela"],
};

export const areasByCity: Record<string, string[]> = {
    "Bangalore": ["Indiranagar", "Koramangala", "Whitefield", "Jayanagar", "HSR Layout", "Marathahalli", "BTM Layout", "Rajajinagar"],
    "Mumbai": ["Andheri", "Bandra", "Powai", "Thane", "Borivali", "Malad"],
    "Chennai": ["Anna Nagar", "T. Nagar", "Adyar", "Velachery", "Mylapore"],
    "Hyderabad": ["Banjara Hills", "Jubilee Hills", "Madhapur", "Gachibowli", "Kondapur"],
    "Pune": ["Koregaon Park", "Baner", "Kothrud", "Viman Nagar", "Hadapsar"],
    "Delhi": ["Saket", "Lajpat Nagar", "Dwarka", "Rohini", "Vasant Kunj"],
    "New Delhi": ["Saket", "Lajpat Nagar", "Dwarka", "Rohini", "Vasant Kunj"],
    "Kochi": ["Kakkanad", "Edapally", "Palarivattom", "Aluva"],
};

export const academies = [
    {
        id: 1,
        name: "Muzigal Academy - Indiranagar",
        address: "1st Floor, 100 Feet Road, Indiranagar, Bangalore - 560038",
        area: "Indiranagar",
        city: "Bangalore",
        state: "Karnataka",
        phone: "+91 98765 43210",
        rating: 4.8,
        reviews: 124,
        subjects: ["Guitar", "Piano", "Keyboard", "Vocals", "Drums"],
        image: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=400&q=80",
    },
    {
        id: 2,
        name: "Muzigal Academy - Koramangala",
        address: "3rd Cross, 5th Block, Koramangala, Bangalore - 560095",
        area: "Koramangala",
        city: "Bangalore",
        state: "Karnataka",
        phone: "+91 98765 43211",
        rating: 4.7,
        reviews: 98,
        subjects: ["Guitar", "Violin", "Piano", "Carnatic Vocals"],
        image: "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=400&q=80",
    },
    {
        id: 3,
        name: "Muzigal Academy - HSR Layout",
        address: "27th Main Road, Sector 2, HSR Layout, Bangalore - 560102",
        area: "HSR Layout",
        city: "Bangalore",
        state: "Karnataka",
        phone: "+91 98765 43212",
        rating: 4.9,
        reviews: 156,
        subjects: ["Drums", "Guitar", "Piano", "Flute", "Tabla"],
        image: "https://images.unsplash.com/photo-1524230572899-a752b3835840?w=400&q=80",
    },
    {
        id: 4,
        name: "Muzigal Academy - Anna Nagar",
        address: "42nd Street, 7th Avenue, Anna Nagar, Chennai - 600040",
        area: "Anna Nagar",
        city: "Chennai",
        state: "Tamil Nadu",
        phone: "+91 98765 43213",
        rating: 4.6,
        reviews: 87,
        subjects: ["Carnatic Vocals", "Violin", "Mrudangam", "Keyboard"],
        image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&q=80",
    },
    {
        id: 5,
        name: "Muzigal Academy - Banjara Hills",
        address: "Road No. 12, Banjara Hills, Hyderabad - 500034",
        area: "Banjara Hills",
        city: "Hyderabad",
        state: "Telangana",
        phone: "+91 98765 43214",
        rating: 4.8,
        reviews: 113,
        subjects: ["Guitar", "Piano", "Vocals", "Drums", "Saxophone"],
        image: "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=400&q=80",
    },
    {
        id: 6,
        name: "Muzigal Academy - Koregaon Park",
        address: "Lane 5, Koregaon Park, Pune - 411001",
        area: "Koregaon Park",
        city: "Pune",
        state: "Maharashtra",
        phone: "+91 98765 43215",
        rating: 4.7,
        reviews: 92,
        subjects: ["Piano", "Guitar", "Keyboard", "Western Vocals"],
        image: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=400&q=80",
    },
];
